### ISSUE TITLE
bin/rails test test/system fails with timeout

### ISSUE THREAD

**Issue by naofumi-fujii** [test-unit/test-unit-rails#15]
i built an sample app with simple scaffold here.
https://github.com/naofumi-fujii/my-sample-rails

adding test-unit-rails and running  `bin/rails test test/system` fails.

the code is 
https://github.com/naofumi-fujii/my-sample-rails/pull/1

error
--
```
Error: test: visiting the index(UsersTest): Net::ReadTimeout: Net::ReadTimeout
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:176:in `rbuf_fill'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:154:in `readuntil'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/protocol.rb:164:in `readline'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http/response.rb:40:in `read_status_line'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http/response.rb:29:in `read_new'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1446:in `block in transport_request'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1443:in `catch'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1443:in `transport_request'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1416:in `request'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1409:in `block in request'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:877:in `start'
/Users/naofumi_fujii/.rbenv/versions/2.4.0/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/http/default.rb:124:in `response_for'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/http/default.rb:78:in `request'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/http/common.rb:61:in `call'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/bridge.rb:170:in `execute'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/oss/bridge.rb:579:in `execute'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/remote/oss/bridge.rb:52:in `get'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/selenium-webdriver-3.4.4/lib/selenium/webdriver/common/navigation.rb:32:in `to'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/capybara-2.14.4/lib/capybara/selenium/driver.rb:67:in `visit'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/capybara-2.14.4/lib/capybara/session.rb:269:in `visit'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/vendor/bundle/gems/capybara-2.14.4/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
/Users/naofumi_fujii/src/github.com/naofumi-fujii/my-sample-rails/test/system/users_test.rb:5:in `block in <class:UsersTest>'
```

**Comment by kou** [comment]
Thanks for your report.
I've fixed it in test-unit-activesupport. Please update your test-unit-activesupport.
